### ISSUE TITLE
Virenalarm ..

### ISSUE THREAD

**Issue by Pierre-de-la-Verre** [geoboxag/GEOBOX.OSC.DisplayModelEditor#1]
Beim Start der aktuellen Exe sehe ich das:
![grafik](https://user-images.githubusercontent.com/13277944/120475119-43d73a00-c3a9-11eb-952b-2f36e84b152d.png)
Weitergeklickt habe ich nicht.

**Comment by urss1** [comment]
Dies ist eine Standard-Meldung vom Windows, in der Regel kommt diese wenn eine EXE (oder weitere Dateien) aus dem Internet heruntergeladen wurde und ausgeführt wird.

Wir haben keinen Virus hineinprogrammiert (soweit unser Empfinden dafür), ist eigentlich kein "Virusalarm" sondern eine Sicherheitsmeldung für die Ausführung.

Wir arbeiten an einer möglichen Lösung, damit diese Meldung nicht mehr erscheint.
Bis zu einer Lösung bleiben folgende Möglichkeiten:
- Uns Vertrauen oder unser Code interpretieren und mit der Schaltfläche "Trotzdem ausführen" die Software verwenden.
- Den Code herunteralden und selber Compilieren.
- "Nicht ausführen" und somit das Tool nicht verwenden.

**Comment by urss1** [comment]
@Pierre-de-la-Verre: Wir haben einen Installer hinzugefügt, in der Hoffnung, dass mit einer Installation der Software diese Meldung nicht mehr angezeigt wird.
