### ISSUE TITLE
Unklare Parameterwerte

### ISSUE THREAD

**Issue by Pierre-de-la-Verre** [geoboxag/GEOBOX.OSC.DisplayModelEditor#2]
Hier werden meine Werte ersetzt und die (Geobox?)-Werte eingetragen:

```
        <Parameter>
          <Name>DataStore</Name>
          <Value>GBX_DEV_FA</Value>
        </Parameter>
        <Parameter>
          <Name>Service</Name>
          <Value>topobase</Value>
        </Parameter>
        <Parameter>
          <Name>Username</Name>
          <Value>MAPSYS</Value>
        </Parameter>
```

Ist das so richtig?

**Comment by urss1** [comment]
Ja, dies ist korrekt und genau was die 1-Klick-Wartung zu tun hat.
Wenn ein Darstellungsmodell mit dem Autodesk AutoCAD Map 3D gespeichert wird, steht jeweils die Verbindung zu der aktuellen Fachschale in den Parmater.
Diese Parameter werden durch die Bereinigungsfunktion überschrieben.

Welche Werte geschrieben werden sollen, kann in der Config-Datei geändert werden.

**Comment by urss1** [comment]
Ist nun in der ReadMe Datei dokumentiert.
