### ISSUE TITLE
gemerkte Einstellungen?

### ISSUE THREAD

**Issue by Pierre-de-la-Verre** [geoboxag/GEOBOX.OSC.DisplayModelEditor#3]
Nach jedem Start steht der Root-Pfad auf "C:\_M3D_DisplayModel". Sollte die Einstellung nicht gespeichert werden?

**Comment by urss1** [comment]
Werden nicht in den Einstellungen gespeichert, da sich dieser auch nicht permanent ändert (oder ändern sollte).
In der Software werden keine benutzerdefinierten Einstellungen gehandhabt.
Der "Root-Pfad" kann in der Config-Datei (GEOBOX.OSC.DisplayModelEditor.exe.config) eingestellt werden.

**Comment by urss1** [comment]
Ist nun in der ReadMe Datei dokumentiert.
