### ISSUE TITLE
Änderung von schreibgeschützten Daten

### ISSUE THREAD

**Issue by Pierre-de-la-Verre** [geoboxag/GEOBOX.OSC.DisplayModelEditor#4]
Der grüne Haken für "Datei bereinigt" erscheint auch, wenn die Datei schreibgeschützt ist und gar nicht geändert wurde.

**Comment by urss1** [comment]
Leider wird der Status akutell nicht korrekt angezeigt.
Nehmen wir gerne für eine kommende Version auf und bereinigen diesen Umstand.

**Comment by Pierre-de-la-Verre** [comment]
Gibt es einen Veröffentlichungsplan für die nächsten Versionen?

**Comment by urss1** [comment]
Wurde erledigt.
