### ISSUE TITLE
Darstellungsmodell auswählen

### ISSUE THREAD

**Issue by Pierre-de-la-Verre** [geoboxag/GEOBOX.OSC.DisplayModelEditor#5]
Wenn man das Darstellungsmodell nicht per Menü wählt, sondern den Pfad aus der Zwischenablage einfügt, dann wird das nicht akzeptiert.

**Comment by urss1** [comment]
Besten Dank, nehmen wir gerne als Änderung für eine kommende Version auf.

**Comment by urss1** [comment]
Die Pfad-Angaben werden neu als Text angezeigt und nicht mehr als Formular-Element. Somit kann dieser Text nicht mehr aus der Zwischenablage direkt auf dem UI eingefügt werden.
Der Pfad aus der Zwischenablage kann aber beim Datei-Öffnen Dialog verwendet werden um schnell an den gewünschten Ort in der Dateiablage zu kommen.
