### ISSUE TITLE
Config-Datei unveränderbar

### ISSUE THREAD

**Issue by Pierre-de-la-Verre** [geoboxag/GEOBOX.OSC.DisplayModelEditor#6]
Die Config-Datei liegt bei einer normalen Installation in "c:\program Files\..." und ist dort eigentlich schreibgeschützt. Die Datei müsste eigentlich woanders liegen.

**Comment by urss1** [comment]
Das bearbeiten dieser Datei erfordert lediglich erhöte Berechtigung auf dem System. In der Regel kann diese Datei mit einem Text-Editor ohne weiteres Berarbeitet werden.

Falls es unter keinen Umständen erlaubt wird, diese Datei zu ändern, kann als Alternative die EXE.ZIP heruntergeladen und die Dateien in ein beliebiges Verzeichnis entpackt werden. Dann kann auch die config-Datei geändert werden.
