### ISSUE TITLE
Vorschlag: Anleitung ins Setup packen

### ISSUE THREAD

**Issue by Pierre-de-la-Verre** [geoboxag/GEOBOX.OSC.DisplayModelEditor#7]
Ein readme / eine Anleitung könnte / sollte auch beim Setup mitinstalliert werden.

**Comment by urss1** [comment]
Das "readme" mit der Anleitung ist eine Datei im MD (Mark-Down) Format, dies benötigt eine zusätzliche Software auf dem Desktop um diese leserlich Darzustellen.
Auf der Projektseite wird dies übernommen und entsprechend angezeigt.
Wir empfinden es als bessere Lösung, die aktuelle Anleitung jeweils auf der Projektseite zu veröffentlichen und für jeden Einsehbar bereitzustellen.
